openapi: 3.0.0
info:
  title: Hotel Posada Real
  description: Optional multiline or single-line description in HTML.
  version: 0.0.1
servers:
  - url: http://localhost:3001/api/v1
    description: local
paths:
  /rooms:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string